# Generated by Django 5.1 on 2025-09-27 05:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventoryitem',
            name='specs_override',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
