# Generated by Django 5.1 on 2025-09-27 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_inventoryitem_specs_override'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventoryitem',
            name='discount_description',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='inventoryitem',
            name='discount_type',
            field=models.CharField(blank=True, choices=[('percentage', 'Percentage Off'), ('fixed', 'Fixed Amount Off'), ('cashback', 'Cashback')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='inventoryitem',
            name='discount_value',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
