# Generated by Django 5.1 on 2025-09-27 08:00

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_inventoryitem_discount_description_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='vehicleimage',
            options={'ordering': ['order']},
        ),
        migrations.RemoveField(
            model_name='vehicleimage',
            name='alt_text',
        ),
        migrations.RemoveField(
            model_name='vehicleimage',
            name='inventory_item',
        ),
        migrations.AddField(
            model_name='branch',
            name='location_details',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='branch',
            name='zipcode',
            field=models.CharField(default='523001', max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='vehicleimage',
            name='vehicle',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='images', to='core.vehiclemodel'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='vehiclemodel',
            name='added_on',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='vehiclemodel',
            name='dealer',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='core.dealership'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='vehiclemodel',
            name='is_featured',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='vehiclemodel',
            name='price',
            field=models.DecimalField(decimal_places=2, default=90000, max_digits=12),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='vehiclemodel',
            name='status',
            field=models.CharField(choices=[('AVAILABLE', 'Available'), ('SOLD', 'Sold'), ('HOLD', 'Hold')], default='AVAILABLE', max_length=20),
        ),
        migrations.AlterField(
            model_name='vehiclemodel',
            name='brand',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.brand'),
        ),
        migrations.AlterField(
            model_name='vehiclemodel',
            name='fuel_type',
            field=models.CharField(blank=True, choices=[('PETROL', 'Petrol'), ('ELECTRIC', 'Electric'), ('HYBRID', 'Hybrid')], max_length=20, null=True),
        ),
    ]
