# Generated by Django 5.1 on 2025-09-27 08:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_vehicleimage_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehiclemodel',
            name='branch',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='vehicles', to='core.branch'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='vehiclemodel',
            name='discount_description',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='vehiclemodel',
            name='discount_type',
            field=models.CharField(blank=True, choices=[('percentage', 'Percentage Off'), ('fixed', 'Fixed Amount Off'), ('cashback', 'Cashback')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='vehiclemodel',
            name='discount_value',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='vehiclemodel',
            name='stock',
            field=models.IntegerField(default=0),
        ),
    ]
