# Generated by Django 5.1 on 2025-09-27 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_vehiclemodel_branch_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehiclemodel',
            name='type',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
