# Generated by Django 5.1 on 2025-09-27 08:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_vehiclemodel_created_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='branch',
            name='latitude',
        ),
        migrations.RemoveField(
            model_name='branch',
            name='longitude',
        ),
        migrations.RemoveField(
            model_name='vehiclemodelvariant',
            name='vehicle_model',
        ),
        migrations.AddField(
            model_name='vehiclemodel',
            name='variant',
            field=models.ForeignKey(default=3, on_delete=django.db.models.deletion.CASCADE, to='core.vehiclemodelvariant'),
            preserve_default=False,
        ),
    ]
