# Generated by Django 5.1 on 2025-09-27 08:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_remove_branch_latitude_remove_branch_longitude_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vehiclemodel',
            name='variant',
        ),
        migrations.AddField(
            model_name='vehiclemodelvariant',
            name='vehicle_model',
            field=models.ForeignKey(default=3, on_delete=django.db.models.deletion.CASCADE, related_name='variants', to='core.vehiclemodel'),
            preserve_default=False,
        ),
    ]
