# Generated by Django 5.1 on 2025-09-27 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_remove_vehiclemodel_variant_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vehicleimage',
            name='image_url',
        ),
        migrations.AddField(
            model_name='vehicleimage',
            name='image',
            field=models.ImageField(default=1, upload_to='vehicles/'),
            preserve_default=False,
        ),
    ]
