# Generated by Django 5.1 on 2025-09-27 11:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_remove_vehicleimage_image_url_vehicleimage_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehiclemodel',
            name='branch',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='branches', to='core.branch'),
        ),
    ]
