# Generated by Django 5.1 on 2025-09-27 13:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_alter_vehiclemodel_branch'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='listing',
        ),
        migrations.AlterModelOptions(
            name='vehicleimage',
            options={'ordering': ['-id']},
        ),
        migrations.AddField(
            model_name='review',
            name='vehicle',
            field=models.ForeignKey(default=13, on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='core.vehiclemodel'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='vehiclemodel',
            name='approved',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='vehiclemodel',
            name='condition',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
        migrations.AddField(
            model_name='vehiclemodel',
            name='exchange_offer',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='vehiclemodel',
            name='km_driven',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='vehiclemodel',
            name='loan_option',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='vehiclemodel',
            name='seller',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='used_listings', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='vehiclemodel',
            name='specs',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='vehiclemodel',
            name='year',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='vehiclemodel',
            name='branch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='branches', to='core.branch'),
        ),
        migrations.AlterField(
            model_name='vehiclemodel',
            name='dealer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.dealership'),
        ),
        migrations.AlterField(
            model_name='vehiclemodel',
            name='type',
            field=models.CharField(choices=[('NEW', 'New'), ('USED', 'Used')], default='New', max_length=50),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='UsedBikeListing',
        ),
    ]
