# Generated by Django 5.1 on 2025-09-27 14:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_remove_review_listing_alter_vehicleimage_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehiclemodel',
            name='variant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vehicle_instances', to='core.vehiclemodelvariant'),
        ),
    ]
