# Generated by Django 5.1 on 2025-09-27 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_vehiclemodel_variant'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehiclemodel',
            name='model_name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
