# Generated by Django 5.1 on 2025-09-27 18:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_vehiclemodel_model_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vehiclemodel',
            name='base_specs',
        ),
    ]
