# Generated by Django 5.1 on 2025-09-28 01:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_remove_vehiclemodel_base_specs'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vehiclemodel',
            name='stock',
        ),
        migrations.AlterField(
            model_name='vehiclemodel',
            name='fuel_type',
            field=models.CharField(choices=[('PETROL', 'Petrol'), ('ELECTRIC', 'Electric'), ('HYBRID', 'Hybrid')], default='PETROL', max_length=20),
            preserve_default=False,
        ),
    ]
